### ISSUE TITLE
I can't seem to run this

### ISSUE THREAD

**Issue by leonnn1** [cloneofsimo/paint-with-words-sd#11]
I am getting this error, I don't know if I have done something wrong.

 File "B:\paint-with-words-sd\paint_with_words\paint_with_words.py", line 174, in _tokens_img_attention_weight
    assert is_in == 1, f"token {v_as_tokens} not found in text"

![image](https://user-images.githubusercontent.com/85142472/201507251-1e5f617d-bf0b-4072-8f07-5d10f0f179d0.png)

**Comment by cloneofsimo** [comment]
Say you have a `input_prompt = "a rabbit and a cat"`.
and you have text-labeled segmentation maps with region with `dog` in it. In this current implementation, this will cause an error because `dog` is not in the `input_prompt`.
**Make sure that that all your segmentation labels are strictly include in the prompt.**

Note : This is, to be honest, not the best way to implement as there can always be subtle difference in segmentation label and prompt, which is reasonable! I am planning to thus implement some sort of "neural" version of this, but this was not in their paper so I don't know if this would work.

**Comment by leonnn1** [comment]
thank you, I mannaged to make it work, I am still a bit lost but it's doing something haha, great work by the way!

**Comment by hiss-remi** [comment]
> Say you have a `input_prompt = "a rabbit and a cat"`. and you have text-labeled segmentation maps with region with `dog` in it. In this current implementation, this will cause an error because `dog` is not in the `input_prompt`. **Make sure that that all your segmentation labels are strictly include in the prompt.**

The thing that was tripping me up is that if you have multiple words for a given region, it won't trigger this error as long as one of the words is in your prompt. Unfortunately, words that aren't in the prompt usually don't seem to have any effect on the output image, while words that are in the prompt that *could* apply to the subjects of multiple regions frequently end up contaminating them. Which makes using this for complicated subjects a bit of a crapshoot.

(Although the lack of negative prompting is sometimes making it hard to tell what's going on... the model I'm using is very good at making bad art if you don't tell it not to.)

**Comment by cloneofsimo** [comment]
> _could_ apply to the subjects of multiple regions frequently end up contaminating them. Which makes using this for complicated subjects a bit of a crapshoot.

Right, I am aware of this issue. This *is* fixable problem and I will work on it.


> (Although the lack of negative prompting is sometimes making it hard to tell what's going on... the model I'm using is very good at making bad art if you don't tell it not to.)

I have added negative prompting today, so check it out!
you can use it with arguement `unconditional_input_prompt: str = "",`

**Comment by hiss-remi** [comment]
> Right, I am aware of this issue. This _is_ fixable problem and I will work on it.

Glad to hear it. I... don't really get how *any* of this works, so I wasn't sure what I should hope for.
