### ISSUE TITLE
Switch to SD v1.5

### ISSUE THREAD

**Issue by danielshemeshisrael** [cloneofsimo/paint-with-words-sd#12]
Is it possible to use this in v1.5 instead of v1.4?

**Comment by 0xdevalias** [comment]
This is documented in the README already:

- https://github.com/cloneofsimo/paint-with-words-sd#using-other-fine-tuned-models

**Comment by 0xdevalias** [comment]
> I made a simple colab example just now, you can try it out here: [paint-with-words colab](https://colab.research.google.com/drive/1MZfGaY3aQQn5_T-6bkXFE1rI59A2nJlU?usp=sharing)
> 
> _Originally posted by @shreydan in https://github.com/cloneofsimo/paint-with-words-sd/issues/4#issuecomment-1312768401_

You can confirm the above `hf_model_path` change on the colab mentioned here by editing the cell that has the `img = paint_with_words(` (first cell after the 'Run Model' heading)

We can also explicitly set the `seed` parameter here as well, to make comparisons between the 2 models easier.

### Original version using SD v1.4

![image](https://user-images.githubusercontent.com/753891/201799566-1c948fb1-016a-46c6-b47c-81191db09197.png)
![image](https://user-images.githubusercontent.com/753891/201799588-e6db1077-21c1-49fc-8567-c68b4d451703.png)


### New version using SD v1.5

![image](https://user-images.githubusercontent.com/753891/201799812-257249c4-7293-4928-95c7-ea769a5c4c42.png)
![image](https://user-images.githubusercontent.com/753891/201799849-b4370831-350e-44b6-bb2a-24b0c23abfba.png)

**Comment by hiss-remi** [comment]
> You can see that `pww_load_tools` takes a `hf_model_path` and/or `local_model_path ` here:

One advantage of this method that you can also change the scheduler, which might be desirable for performance or quality issues. (I found recently that the model I'm using often has blatant graphical issues even with a large step count on LMS, but EulerAncestralDiscreteScheduler or EulerDiscreteScheduler do much better. Just don't forget to import your scheduler of choice from diffusers. (Something the example currently doesn't show.)

**Comment by cloneofsimo** [comment]
Nice note @hiss-remi , ill add this feature as well.
