### ISSUE TITLE
inj_forward() got an unexpected keyword argument 'attention_mask'

### ISSUE THREAD

**Issue by wdkwdkwdk** [cloneofsimo/paint-with-words-sd#23]
I run the sample code, but got this error

diffusers version : 0.11.1

**Comment by nistvan86** [comment]
Same here, try to run the sample code but it exists with this.

**Comment by cloneofsimo** [comment]
Thanks for the solution!

**Comment by wdkwdkwdk** [comment]
> 

Thanks a lot, problem solved
