### ISSUE TITLE
inj_forward() got an unexpected keyword argument 'encoder_hidden_states'

### ISSUE THREAD

**Issue by OlegBatrakov** [cloneofsimo/paint-with-words-sd#26]
Hey, I've been trying to run runer.py, however get this error.
Can you please advise me?
<img width="935" alt="Снимок экрана 2023-02-01 163056" src="https://user-images.githubusercontent.com/9624129/216125425-9012d317-5098-4b0c-9cae-e033bc8aa61b.png">

**Comment by OlegBatrakov** [comment]
Soorry, already solved diffusers 0.9.0 should be used
pip install diffusers==0.9.0

**Comment by lwchen6309** [comment]
This issue dues to a diffusers version > 0.10.0, it's now add to requirement.txt to set diffusers==0.10.0 to avoid this issue
