### ISSUE TITLE
Will the Gradio demo look something like this?

### ISSUE THREAD

**Issue by ninjasaid2k** [cloneofsimo/paint-with-words-sd#32]
![willthegradiodemoincludesomethinglikethis](https://user-images.githubusercontent.com/99513716/222534129-90d1fd44-130c-44d6-b6a9-e04058e71d7b.PNG)
![willthegradiodemoincludesomethinglikethis2](https://user-images.githubusercontent.com/99513716/222534274-a386f8d9-0b0f-4d5f-9f97-cbd397337658.PNG)

Source: https://huggingface.co/spaces/weizmannscience/multidiffusion-region-based

**Comment by lwchen6309** [comment]
Thanks for the inspiring gradio ui, this would be considered in the future update :)

**Comment by lwchen6309** [comment]
This has been implemented in the latest update
