### ISSUE TITLE
Can you make a Colab notebook for the noobs?

### ISSUE THREAD

**Issue by danielshemeshisrael** [cloneofsimo/paint-with-words-sd#4]

**Comment by cloneofsimo** [comment]
Sure

**Comment by fallenangel3k** [comment]
that would be awesome. thanks

**Comment by shreydan** [comment]
hello @fallenangel3k @cloneofsimo  

I made a simple colab example just now, you can try it out here: [paint-with-words colab](https://colab.research.google.com/drive/1MZfGaY3aQQn5_T-6bkXFE1rI59A2nJlU?usp=sharing)

**Comment by cloneofsimo** [comment]
Thanks! that's awesome!

**Comment by 0xdevalias** [comment]
@cloneofsimo It would be awesome if this was able to be added to the README

**Comment by cloneofsimo** [comment]
> I would like to do this as a pull request if that's okay with some more changes to the colab notebook.

Sure! that would be nice

**Comment by shreydan** [comment]
#15 opened a pull request for the colab notebook

**Comment by cloneofsimo** [comment]
@shreydan thank you for the contribution!

**Comment by shreydan** [comment]
Thank you @cloneofsimo

**Comment by cloneofsimo** [comment]
I've also added textual inversion example [here](https://github.com/cloneofsimo/paint-with-words-sd/blob/master/contents/notebooks/paint_with_words_textual_inversion.ipynb).
