### ISSUE TITLE
Is there a way to use with other models?

### ISSUE THREAD

**Issue by hiss-remi** [cloneofsimo/paint-with-words-sd#6]
Just what the topic says.

**Comment by cloneofsimo** [comment]
Yes, certainly. I'm planning to add this feature as well. Needs major refactoring tho

**Comment by cloneofsimo** [comment]
If you are developer, you can replace first two argument of loaded materials to replace the model you wish and by swapping forward function. If you have "original checkpoints", (ones that are often used in a1111 repo), you can use this [script](https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py) to transform them into HF diffuser format.

**Comment by cloneofsimo** [comment]
You can now convert LDM model format (ones that are used in a1111 repos, or sd-original.ckpt formats) with paint-with-words.
Mitigated by https://github.com/cloneofsimo/paint-with-words-sd/commit/f86c6fd1f46de28dff479ba9620b65d9e435a95e
