### ISSUE TITLE
Torch missing

### ISSUE THREAD

**Issue by DoctorMG** [cloneofsimo/paint-with-words-sd#7]
there is an import of torch required, that seems to be missing in requirements.txt

should be added or documented

**Comment by some9000** [comment]
What a coincidence I am currently looking into exactly that. It being reliant on some things that are imported by other scripts. Cleaning that part up.
Thanks for letting me know!

**Comment by cloneofsimo** [comment]
Well I thought torch part is kind of trivial because stable diffusion is built on torch...
Im also not that aware of making appropriate setuptools to automatically handle various os-cudakernel dependent torch setups
Any help would be appreciated

**Comment by DoctorMG** [comment]
Hm, me neither. What I did to install torch was just this:
**x:\> pip install torch torchvision torchaudio**

When I execute paint_with_words after this pip the break by missing torch is gone. There is some warning smalltalk like "no CUDA found", "will need longer time" (... sure ...) but they all start with "WARNING". So I guess these are no show stoppers and the pip command for installation is ok.

Since I get a hard exception failure shortly later I don't know if there is something else missing beyound torch.

**Comment by cloneofsimo** [comment]
Right, like the CLIP repo, ill just add more info on installing pytorch.
