### ISSUE TITLE
Cannot reproduce results

### ISSUE THREAD

**Issue by helia95** [cloneofsimo/paint-with-words-sd#9]
Hi, when running `runner.py` I obtain different results from the ones showed in readme file
 
![aurora_0 5-full moon_1 5-mountains_0 4-a half-frozen lake_0 3-boat_2 0](https://user-images.githubusercontent.com/49465595/201422504-26dc1bd0-8236-4b6b-af1d-a4d342454440.png)

this is what I got using `EXAMPLE_SETTING_3`. 
I tried increasing the strength of "full moon" and "boat", I'm able to obtain the moon but the boat never showed up.

Any guess?

**Comment by cloneofsimo** [comment]
Try the code with this

```python
img = paint_with_words(
        color_context=color_context,
        color_map_image=color_map_image,
        input_prompt=input_prompt,
        num_inference_steps=30,
        guidance_scale=7.5,
        device="cuda:0",
        weight_function=lambda w, sigma, qk: 0.4 * w * math.log(1 + sigma) * qk.max(),
    )
```
I made update to have default weight function to 0.1 * w * math.log(1 + sigma) * qk.max(), and readme was made before that.

**Comment by cloneofsimo** [comment]
Should get : 
![image](https://user-images.githubusercontent.com/35953539/201426766-7a3314ad-345c-401d-b6a0-d6f0cdefc903.png)

**Comment by helia95** [comment]
Thanks, it works now!
